global:
  imagePullPolicy: IfNotPresent
  ###vault:
  ###  host: ip
  ###  name: vault
  ###  vaultToken: someToken

frontend:
  replicas: 1
  revisionHistoryLimit: 15
  strategy:
    type: Recreate
  service:
    port: 80
  ingress:
    host: boev.2sem.students-projects.ru
    secretName: 2sem-students-projects-wildcard-secret
    path: /
    pathType: Prefix
  containerPort: 80
  image: b0ev/sausage-frontend:latest
  resources:
    requests:
      cpu: 100m
      memory: 96Mi
    limits:
      cpu: 200m
      memory: 180Mi
  nginxConf: nginx.conf

backend:
  replicas: 1
  revisionHistoryLimit: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  service:
    port: 8080
  containerPort: 8080
  image: b0ev/sausage-backend:latest
  annotations:
    port: 8080
    path: /actuator/prometheus
    scrape: "true"
  env:
    postgresUri: jdbc:postgresql://postgresql:5432/sausage-store
    postgresUser: store
    postgresPassword: storepassword
    reportPath: /logs/reports
    logPath: /logs
  resources:
    requests:
      cpu: 600m
      memory: 200Mi
    limits:
      cpu: 800m
      memory: 700Mi
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 1
    failureThreshold: 3
  vpa:
    updatePolicy:
      updateMode: "Off"
    resourcePolicy:
      containerPolicies:
        - containerName: "*"
          minAllowed:
            cpu: 300m
            memory: 180Mi
          maxAllowed:
            cpu: 800m
            memory: 800Mi
          controlledResources: ["cpu", "memory"]

backend-report:
  replicas: 1
  strategy:
    type: Recreate
  image: b0ev/sausage-backend-report:latest
  service:
    port: 8080
  config:
    port: 8080
  containerPort: 8080
  secret:
    dbport: 27017
    dbhost: mongodb
    dbname: sausage-store
    dbuser: reports
    dbpassword: reportspassword
  resources:
    requests:
      cpu: 150m
      memory: 96Mi
    limits:
      cpu: 300m
      memory: 180Mi
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70

infra:
  mongodb:
    replicas: 1
    image: mongo:8.0.9
    env:
      MONGO_INITDB_DATABASE: sausage-store
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_USERNAME: reports
      MONGO_INITDB_PASSWORD: reportspassword
    containerPort: 27017
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 256Mi

  mongodbInit:
    image: mongo:8.0.9
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 50m
        memory: 128Mi

  postgresql:
    replicas: 1
    image: postgres:17.5
    env:
      POSTGRES_DB: sausage-store
      POSTGRES_USER: store
      POSTGRES_PASSWORD: storepassword
      PGDATA: /var/lib/postgresql/data/pgdata
    containerPort: 5432
    resources:
      requests:
        cpu: 300m
        memory: 250Mi
      limits:
        cpu: 500m
        memory: 500Mi
