global:
  imagePullPolicy: Always
  ###vault:
  ###  host: ip
  ###  name: vault
  ###  vaultToken: someToken


frontend:
### В чарте frontend отсутствуют некоторые важные файлы. Поймите какие и опишите их.
  replicas: 1
  revisionHistoryLimit: 15
  strategy:
    type: Recreate
  service:
    port: 80
  ingress:
    host: boev.students-projects.ru # Корректный домен будет указан в задании
    path: /
    pathType: Prefix
  containerPort: 80
  image: b0ev/sausage-frontend:latest
  resources:
    requests:
      cpu: "200m"
      memory: "128Mi"
    limits:
      cpu: "400m"
      memory: "300Mi"
  nginxConf: nginx.conf

backend:
  annotations:
    path: /actuator/prometheus
    port: "8080"
    scrape: "true"
  env:
    postgresUri: jdbc:postgresql://postgresql:5432/sausage-store
    postgresUser: store
    postgresPassword: storepassword
    reportPath: /logs/reports
    logPath: /logs
  service:
    port: 8080
  revisionHistoryLimit: 15
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  image: b0ev/sausage-backend:latest
  imagePullPolicy: Always
  resources:
    requests:
      cpu: "700m"
      memory: "200Mi"
    limits:
      cpu: "900m"
      memory: "700Mi"
  containerPort: 8080
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 15
    periodSeconds: 30
    timeoutSeconds: 1
    failureThreshold: 6
  vpa:
    updatePolicy:
      updateMode: "Recreate"
    resourcePolicy:
      containerPolicies:
        - containerName: "*"
          minAllowed:
            cpu: 500m
            memory: 200Mi
          maxAllowed:
            cpu: 1200m
            memory: 1Gi
          controlledResources: ["cpu", "memory"]

# backend-report:
# ### Опишите значения для backend-report
# ### Приложение должно использовать стратегию Recreate
# ### Приложение использует переменную PORT - порт, на котором оно запустится и DB - Uri-подключение к mongodb. 
# ### DB положите в Secret, PORT в ConfigMap
# ### Опишите HPA для backend-report

infra:
  mongodb:
    env:
      MONGO_INITDB_DATABASE: sausage-store
      MONGO_INITDB_ROOT_USERNAME: reports
      MONGO_INITDB_ROOT_PASSWORD: reportspassword
    containerPort: 27017

  postgresql:
    env:
      POSTGRES_DB: sausage-store
      POSTGRES_PASSWORD: storepassword
      POSTGRES_USER: store
    containerPort: 5432
